import sys
import argparse
import re

from .api import YoutubeAPI, MusicBrainzAPI
from .album import Album
from .video import Video
from .YoutubeBZ import YoutubeBZ

def main():
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group2 = parser.add_mutually_exclusive_group()
    group2.add_argument('-g', '--generated', help='search for music video auto generated by Youtube (by defaut)', action='store_true')
    group2.add_argument('-a', '--all', help='search for music video not auto generated by Youtube', action='store_false')
    group.add_argument('-m', '--mbid', metavar=('MBID'), help='the mbid of the album')
    group.add_argument('-s', '--search', nargs=2, metavar=('artist', 'album') )

    if len(sys.argv)==1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    args = parser.parse_args()

    if args.search:
        artist, album = args.search
        mbid = YoutubeBZ().search_album(artist, album)
    else:
        if re.search(r'[\w]{8}-[\w]{4}-[\w]{4}-[\w]{4}-[\w]{12}', args.mbid) == None:
            sys.exit('{} not a valid MBID'.format(args.mbid))
        mbid = args.mbid

    YoutubeBZ().find_album(mbid, args.all)
