import html

from .api import YoutubeAPI, MusicBrainzAPI
from .album import Album

from difflib import SequenceMatcher

class YoutubeBZ:
    
    def find_ids(self, mbid: str)-> int:

        counts = 0
        myAlbum = Album(mbid)
        
        with open("{}.txt".format(myAlbum.title), "w") as file:
            for track in myAlbum.tracks:
                query = '+"{}" +"{}" +"{}" +"{}"'.format(
                    myAlbum.artist, myAlbum.title, 
                    track, "Auto-generated by YouTube."
                )
                response = YoutubeAPI().search(query)
                video_title = html.unescape(response['items'][0]['snippet']['title'])
                video_id = response['items'][0]['id']['videoId']

                print(track)

                ratio = SequenceMatcher(None, track.upper(), video_title.upper()).ratio() 
                if ratio > 0.9:
                    print(video_title)
                    print()
                    counts = counts + 1

        return counts
