"""
This type stub file was generated by pyright.
"""

from pytube.version import __version__
from pytube.streams import Stream
from pytube.captions import Caption
from pytube.query import CaptionQuery, StreamQuery
from pytube.__main__ import YouTube
from pytube.contrib.playlist import Playlist
from pytube.contrib.channel import Channel
from pytube.contrib.search import Search

"""
Pytube: a very serious Python library for downloading YouTube Videos.
"""
__title__ = ...
__author__ = ...
__license__ = ...
__js__ = ...
__js_url__ = ...

__all__ = ['YouTube', 'Stream']