"""
This type stub file was generated by pyright.
"""

from pytube.__main__ import YouTube
from pytube.captions import Caption
from pytube.contrib.channel import Channel
from pytube.contrib.playlist import Playlist
from pytube.contrib.search import Search
from pytube.query import CaptionQuery, StreamQuery
from pytube.streams import Stream
from pytube.version import __version__

"""
Pytube: a very serious Python library for downloading YouTube Videos.
"""
__title__ = ...
__author__ = ...
__license__ = ...
__js__ = ...
__js_url__ = ...

__all__ = ["YouTube", "Stream"]
