"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional

class Monostate:
    def __init__(self, on_progress: Optional[Callable[[Any, bytes, int], None]], on_complete: Optional[Callable[[Any, Optional[str]], None]], title: Optional[str] = ..., duration: Optional[int] = ...) -> None:
        ...
    


