# Forked from https://github.com/psf/black/blob/main/.github/workflows/lint.yml
name: Lint

on: [push, pull_request]

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Assert PR target is main
        if: github.event_name == 'pull_request' && github.repository == 'psf/black'
        run: |
          if [ "$GITHUB_BASE_REF" != "main" ]; then
              echo "::error::PR targeting '$GITHUB_BASE_REF', please refile targeting 'main'." && exit 1
          fi

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "*"

      - name: black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./youtube_bz ./tests"

      - name: isort
        uses: isort/isort-action@v1
        with:
          configuration: "--check-only --diff --profile=black"