name: tests

on: [push, pull_request]

env:
  default-python: "3.12"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.default-python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.default-python }}
    - name: Upgrade pip, Install nox
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Lint
      run: |
        nox --error-on-missing-interpreters --non-interactive --session lint

  tests:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        include:
          - os: windows-latest
            python-version: "3.12"
          - os: macos-latest
            python-version: "3.12"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: pytest
      run: |
        nox --non-interactive --session tests-${{ matrix.python-version }}
